### PR TITLE
README: Add contributing section

### PR DESCRIPTION
**Pull request by andrealmeid**
Add a contributing section to help new contributors.

### CODE REVIEW

**Comment by rodrigosiqueira** [comment]
Thanks! Merged with tiny changes, see https://github.com/rodrigosiqueira/kworkflow/commit/303947dbd5f304c4651c7ecc683ccddc1856abe0

**Comment by andrealmeid** [comment]
@rodrigosiqueira what's the difference between the two links?

**Comment by rodrigosiqueira** [comment]
Which link?

**Comment by andrealmeid** [comment]
Now with the tiny changes, we have two links to the guide:

```markdown
...
and don't forget to read our
[Contribuitor's Guide](https://siqueira.tech/doc/kw/content/howtocontribute.html)
(or [howtocontribute file](documentation/content/howtocontribute.rst)).
```

**Comment by rodrigosiqueira** [comment]
On 11/11, André Almeida wrote:
> Now with the tiny changes, we have two links to the guide:
> 
> ```markdown
> ...
> and don't forget to read our
> [Contribuitor's Guide](https://siqueira.tech/doc/kw/content/howtocontribute.html)
> (or [howtocontribute file](documentation/content/howtocontribute.rst)).
> ```

Ahhh, they are the same thing. I added the second one just in case the
website is down.

**Pull request closed without merging**
